CREATE TABLE IF NOT EXISTS AUTHOR (
    ID          BIGINT AUTO_INCREMENT,
    FIRSTNAME   VARCHAR2(255) NOT NULL,
    PATRONYMIC  VARCHAR2(255),
    LASTNAME    VARCHAR2(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS GENRE (
    ID          BIGINT AUTO_INCREMENT,
    NAME        VARCHAR2(255) NOT NULL UNIQUE,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS BOOK (
    ID          BIGINT AUTO_INCREMENT,
    NAME        VARCHAR2(255) NOT NULL,
    GENRE       BIGINT NOT NULL,
    AUTHOR      BIGINT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (GENRE) REFERENCES GENRE(ID),
    FOREIGN KEY (AUTHOR) REFERENCES AUTHOR(ID)
);

CREATE TABLE IF NOT EXISTS COMMENT (
    ID          BIGINT AUTO_INCREMENT,
    TEXT        VARCHAR2(255) NOT NULL,
    BOOK     BIGINT,
    PRIMARY KEY (ID),
    FOREIGN KEY (BOOK) REFERENCES BOOK(ID)
);