INSERT INTO AUTHOR(FIRSTNAME, PATRONYMIC, LASTNAME) VALUES ('ALEKSANDR', 'SERGEEVICH', 'PUSHKIN');
INSERT INTO AUTHOR(FIRSTNAME, PATRONYMIC, LASTNAME) VALUES ('NIKOLAY', 'VASILEVICH', 'GOGOL');
INSERT INTO AUTHOR(FIRSTNAME, PATRONYMIC, LASTNAME) VALUES ('LEV', 'NIKOLAEVICH', 'TOLSTOY');

INSERT INTO GENRE(NAME) VALUES ('STORY');
INSERT INTO GENRE(NAME) VALUES ('PLAY');
INSERT INTO GENRE(NAME) VALUES ('NOVEL');

INSERT INTO BOOK(NAME, GENRE, AUTHOR) VALUES ('EVGENIY ONEGIN',
             (SELECT g.ID FROM GENRE g WHERE g.NAME = 'NOVEL'),
             (SELECT a.ID FROM AUTHOR a WHERE a.FIRSTNAME = 'ALEKSANDR' AND a.PATRONYMIC = 'SERGEEVICH' AND a.LASTNAME = 'PUSHKIN'));
INSERT INTO BOOK(NAME, GENRE, AUTHOR) VALUES ('QUEEN OF SPADES',
             (SELECT g.ID FROM GENRE g WHERE g.NAME = 'STORY'),
             (SELECT a.ID FROM AUTHOR a WHERE a.FIRSTNAME = 'ALEKSANDR' AND a.PATRONYMIC = 'SERGEEVICH' AND a.LASTNAME = 'PUSHKIN'));
INSERT INTO BOOK(NAME, GENRE, AUTHOR) VALUES ('VIY',
             (SELECT g.ID FROM GENRE g WHERE g.NAME = 'STORY'),
             (SELECT a.ID FROM AUTHOR a WHERE a.FIRSTNAME = 'NIKOLAY' AND a.PATRONYMIC = 'VASILEVICH' AND a.LASTNAME = 'GOGOL'));
INSERT INTO BOOK(NAME, GENRE, AUTHOR) VALUES ('SHINEL',
             (SELECT g.ID FROM GENRE g WHERE g.NAME = 'STORY'),
             (SELECT a.ID FROM AUTHOR a WHERE a.FIRSTNAME = 'NIKOLAY' AND a.PATRONYMIC = 'VASILEVICH' AND a.LASTNAME = 'GOGOL'));
INSERT INTO BOOK(NAME, GENRE, AUTHOR) VALUES ('THE GOVERNMENT INSPECTOR',
             (SELECT g.ID FROM GENRE g WHERE g.NAME = 'PLAY'),
             (SELECT a.ID FROM AUTHOR a WHERE a.FIRSTNAME = 'NIKOLAY' AND a.PATRONYMIC = 'VASILEVICH' AND a.LASTNAME = 'GOGOL'));
INSERT INTO BOOK(NAME, GENRE, AUTHOR) VALUES ('WAR AND PEACE',
             (SELECT g.ID FROM GENRE g WHERE g.NAME = 'NOVEL'),
             (SELECT a.ID FROM AUTHOR a WHERE a.FIRSTNAME = 'LEV' AND a.PATRONYMIC = 'NIKOLAEVICH' AND a.LASTNAME = 'TOLSTOY'));
INSERT INTO BOOK(NAME, GENRE, AUTHOR) VALUES ('ANNA KARENINA',
             (SELECT g.ID FROM GENRE g WHERE g.NAME = 'NOVEL'),
             (SELECT a.ID FROM AUTHOR a WHERE a.FIRSTNAME = 'LEV' AND a.PATRONYMIC = 'NIKOLAEVICH' AND a.LASTNAME = 'TOLSTOY'));

INSERT INTO COMMENT(TEXT, BOOK) VALUES ('COMMENTARY 1 FOR: EVGENIY ONEGIN',
             (SELECT b.ID FROM BOOK b WHERE b.NAME = 'EVGENIY ONEGIN'));
INSERT INTO COMMENT(TEXT, BOOK) VALUES ('COMMENTARY 2 FOR: EVGENIY ONEGIN',
             (SELECT b.ID FROM BOOK b WHERE b.NAME = 'EVGENIY ONEGIN'));
INSERT INTO COMMENT(TEXT, BOOK) VALUES ('COMMENTARY 3 FOR: EVGENIY ONEGIN',
             (SELECT b.ID FROM BOOK b WHERE b.NAME = 'EVGENIY ONEGIN'));
INSERT INTO COMMENT(TEXT, BOOK) VALUES ('COMMENTARY FOR: QUEEN OF SPADES',
             (SELECT b.ID FROM BOOK b WHERE b.NAME = 'QUEEN OF SPADES'));
INSERT INTO COMMENT(TEXT, BOOK) VALUES ('COMMENTARY FOR: VIY',
             (SELECT b.ID FROM BOOK b WHERE b.NAME = 'VIY'));
INSERT INTO COMMENT(TEXT, BOOK) VALUES ('COMMENTARY FOR: SHINEL',
             (SELECT b.ID FROM BOOK b WHERE b.NAME = 'SHINEL'));
INSERT INTO COMMENT(TEXT, BOOK) VALUES ('COMMENTARY FOR: THE GOVERNMENT INSPECTOR',
             (SELECT b.ID FROM BOOK b WHERE b.NAME = 'THE GOVERNMENT INSPECTOR'));
INSERT INTO COMMENT(TEXT, BOOK) VALUES ('COMMENTARY FOR: WAR AND PEACE',
             (SELECT b.ID FROM BOOK b WHERE b.NAME = 'WAR AND PEACE'));
INSERT INTO COMMENT(TEXT, BOOK) VALUES ('COMMENTARY FOR: ANNA KARENINA',
             (SELECT b.ID FROM BOOK b WHERE b.NAME = 'ANNA KARENINA'));