INSERT INTO AUTHORS(FIRSTNAME, PATRONYMIC, LASTNAME) VALUES ('ALEKSANDR', 'SERGEEVICH', 'PUSHKIN');
INSERT INTO AUTHORS(FIRSTNAME, PATRONYMIC, LASTNAME) VALUES ('NIKOLAY', 'VASILEVICH', 'GOGOL');
INSERT INTO AUTHORS(FIRSTNAME, PATRONYMIC, LASTNAME) VALUES ('LEV', 'NIKOLAEVICH', 'TOLSTOY');

INSERT INTO GENRES(NAME) VALUES ('STORY');
INSERT INTO GENRES(NAME) VALUES ('PLAY');
INSERT INTO GENRES(NAME) VALUES ('NOVEL');

INSERT INTO BOOKS(NAME, GENRE_ID, AUTHOR_ID) VALUES ('EVGENIY ONEGIN',
             (SELECT g.GENRE_ID FROM GENRES g WHERE g.NAME = 'NOVEL'),
             (SELECT a.AUTHOR_ID FROM AUTHORS a WHERE a.FIRSTNAME = 'ALEKSANDR' AND a.PATRONYMIC = 'SERGEEVICH' AND a.LASTNAME = 'PUSHKIN'));
INSERT INTO BOOKS(NAME, GENRE_ID, AUTHOR_ID) VALUES ('QUEEN OF SPADES',
             (SELECT g.GENRE_ID FROM GENRES g WHERE g.NAME = 'STORY'),
             (SELECT a.AUTHOR_ID FROM AUTHORS a WHERE a.FIRSTNAME = 'ALEKSANDR' AND a.PATRONYMIC = 'SERGEEVICH' AND a.LASTNAME = 'PUSHKIN'));
INSERT INTO BOOKS(NAME, GENRE_ID, AUTHOR_ID) VALUES ('VIY',
             (SELECT g.GENRE_ID FROM GENRES g WHERE g.NAME = 'STORY'),
             (SELECT a.AUTHOR_ID FROM AUTHORS a WHERE a.FIRSTNAME = 'NIKOLAY' AND a.PATRONYMIC = 'VASILEVICH' AND a.LASTNAME = 'GOGOL'));
INSERT INTO BOOKS(NAME, GENRE_ID, AUTHOR_ID) VALUES ('SHINEL',
             (SELECT g.GENRE_ID FROM GENRES g WHERE g.NAME = 'STORY'),
             (SELECT a.AUTHOR_ID FROM AUTHORS a WHERE a.FIRSTNAME = 'NIKOLAY' AND a.PATRONYMIC = 'VASILEVICH' AND a.LASTNAME = 'GOGOL'));
INSERT INTO BOOKS(NAME, GENRE_ID, AUTHOR_ID) VALUES ('THE GOVERNMENT INSPECTOR',
             (SELECT g.GENRE_ID FROM GENRES g WHERE g.NAME = 'PLAY'),
             (SELECT a.AUTHOR_ID FROM AUTHORS a WHERE a.FIRSTNAME = 'NIKOLAY' AND a.PATRONYMIC = 'VASILEVICH' AND a.LASTNAME = 'GOGOL'));
INSERT INTO BOOKS(NAME, GENRE_ID, AUTHOR_ID) VALUES ('WAR AND PEACE',
             (SELECT g.GENRE_ID FROM GENRES g WHERE g.NAME = 'NOVEL'),
             (SELECT a.AUTHOR_ID FROM AUTHORS a WHERE a.FIRSTNAME = 'LEV' AND a.PATRONYMIC = 'NIKOLAEVICH' AND a.LASTNAME = 'TOLSTOY'));
INSERT INTO BOOKS(NAME, GENRE_ID, AUTHOR_ID) VALUES ('ANNA KARENINA',
             (SELECT g.GENRE_ID FROM GENRES g WHERE g.NAME = 'NOVEL'),
             (SELECT a.AUTHOR_ID FROM AUTHORS a WHERE a.FIRSTNAME = 'LEV' AND a.PATRONYMIC = 'NIKOLAEVICH' AND a.LASTNAME = 'TOLSTOY'));

INSERT INTO COMMENTS(TEXT, BOOK_ID) VALUES ('COMMENTARY 1 FOR: EVGENIY ONEGIN',
             (SELECT b.BOOK_ID FROM BOOKS b WHERE b.NAME = 'EVGENIY ONEGIN'));
INSERT INTO COMMENTS(TEXT, BOOK_ID) VALUES ('COMMENTARY 2 FOR: EVGENIY ONEGIN',
             (SELECT b.BOOK_ID FROM BOOKS b WHERE b.NAME = 'EVGENIY ONEGIN'));
INSERT INTO COMMENTS(TEXT, BOOK_ID) VALUES ('COMMENTARY 3 FOR: EVGENIY ONEGIN',
             (SELECT b.BOOK_ID FROM BOOKS b WHERE b.NAME = 'EVGENIY ONEGIN'));
INSERT INTO COMMENTS(TEXT, BOOK_ID) VALUES ('COMMENTARY FOR: QUEEN OF SPADES',
             (SELECT b.BOOK_ID FROM BOOKS b WHERE b.NAME = 'QUEEN OF SPADES'));
INSERT INTO COMMENTS(TEXT, BOOK_ID) VALUES ('COMMENTARY FOR: VIY',
             (SELECT b.BOOK_ID FROM BOOKS b WHERE b.NAME = 'VIY'));
INSERT INTO COMMENTS(TEXT, BOOK_ID) VALUES ('COMMENTARY FOR: SHINEL',
             (SELECT b.BOOK_ID FROM BOOKS b WHERE b.NAME = 'SHINEL'));
INSERT INTO COMMENTS(TEXT, BOOK_ID) VALUES ('COMMENTARY FOR: THE GOVERNMENT INSPECTOR',
             (SELECT b.BOOK_ID FROM BOOKS b WHERE b.NAME = 'THE GOVERNMENT INSPECTOR'));
INSERT INTO COMMENTS(TEXT, BOOK_ID) VALUES ('COMMENTARY FOR: WAR AND PEACE',
             (SELECT b.BOOK_ID FROM BOOKS b WHERE b.NAME = 'WAR AND PEACE'));
INSERT INTO COMMENTS(TEXT, BOOK_ID) VALUES ('COMMENTARY FOR: ANNA KARENINA',
             (SELECT b.BOOK_ID FROM BOOKS b WHERE b.NAME = 'ANNA KARENINA'));

INSERT INTO USERS(USERNAME, PASSWORD, ENABLED) VALUES ('ADMIN', '$2a$10$QvlqgQ0KZEFNed5sUdStEuHlf5Ez.yxfElH2vqm9TvO44ZlafJhuW', TRUE);
INSERT INTO USERS(USERNAME, PASSWORD, ENABLED) VALUES ('GUEST', '$2a$10$QvlqgQ0KZEFNed5sUdStEuHlf5Ez.yxfElH2vqm9TvO44ZlafJhuW', TRUE);

INSERT INTO ROLES(NAME) VALUES ('ROLE_ADMINISTRATOR');
INSERT INTO ROLES(NAME) VALUES ('ROLE_GUEST');

INSERT INTO USER_ROLES(USER_ID, ROLE_ID) VALUES (
             (SELECT u.USER_ID FROM USERS u WHERE u.USERNAME = 'ADMIN'),
             (SELECT r.ROLE_ID FROM ROLES r WHERE r.NAME = 'ROLE_ADMINISTRATOR'));
INSERT INTO USER_ROLES(USER_ID, ROLE_ID) VALUES (
             (SELECT u.USER_ID FROM USERS u WHERE u.USERNAME = 'GUEST'),
             (SELECT r.ROLE_ID FROM ROLES r WHERE r.NAME = 'ROLE_GUEST'));