INSERT INTO AUTHOR(FIRSTNAME, PATRONYMIC, LASTNAME) VALUES ('ALEKSANDR', 'SERGEEVICH', 'PUSHKIN');
INSERT INTO AUTHOR(FIRSTNAME, PATRONYMIC, LASTNAME) VALUES ('NIKOLAY', 'VASILEVICH', 'GOGOL');
INSERT INTO AUTHOR(FIRSTNAME, PATRONYMIC, LASTNAME) VALUES ('LEV', 'NIKOLAEVICH', 'TOLSTOY');

INSERT INTO GENRE(NAME) VALUES ('STORY');
INSERT INTO GENRE(NAME) VALUES ('PLAY');
INSERT INTO GENRE(NAME) VALUES ('NOVEL');

INSERT INTO BOOK(NAME, GENRE_ID, AUTHOR_ID) VALUES ('EVGENIY ONEGIN',
             (SELECT g.GENRE_ID FROM GENRE g WHERE g.NAME = 'NOVEL'),
             (SELECT a.AUTHOR_ID FROM AUTHOR a WHERE a.FIRSTNAME = 'ALEKSANDR' AND a.PATRONYMIC = 'SERGEEVICH' AND a.LASTNAME = 'PUSHKIN'));
INSERT INTO BOOK(NAME, GENRE_ID, AUTHOR_ID) VALUES ('QUEEN OF SPADES',
             (SELECT g.GENRE_ID FROM GENRE g WHERE g.NAME = 'STORY'),
             (SELECT a.AUTHOR_ID FROM AUTHOR a WHERE a.FIRSTNAME = 'ALEKSANDR' AND a.PATRONYMIC = 'SERGEEVICH' AND a.LASTNAME = 'PUSHKIN'));
INSERT INTO BOOK(NAME, GENRE_ID, AUTHOR_ID) VALUES ('VIY',
             (SELECT g.GENRE_ID FROM GENRE g WHERE g.NAME = 'STORY'),
             (SELECT a.AUTHOR_ID FROM AUTHOR a WHERE a.FIRSTNAME = 'NIKOLAY' AND a.PATRONYMIC = 'VASILEVICH' AND a.LASTNAME = 'GOGOL'));
INSERT INTO BOOK(NAME, GENRE_ID, AUTHOR_ID) VALUES ('SHINEL',
             (SELECT g.GENRE_ID FROM GENRE g WHERE g.NAME = 'STORY'),
             (SELECT a.AUTHOR_ID FROM AUTHOR a WHERE a.FIRSTNAME = 'NIKOLAY' AND a.PATRONYMIC = 'VASILEVICH' AND a.LASTNAME = 'GOGOL'));
INSERT INTO BOOK(NAME, GENRE_ID, AUTHOR_ID) VALUES ('THE GOVERNMENT INSPECTOR',
             (SELECT g.GENRE_ID FROM GENRE g WHERE g.NAME = 'PLAY'),
             (SELECT a.AUTHOR_ID FROM AUTHOR a WHERE a.FIRSTNAME = 'NIKOLAY' AND a.PATRONYMIC = 'VASILEVICH' AND a.LASTNAME = 'GOGOL'));
INSERT INTO BOOK(NAME, GENRE_ID, AUTHOR_ID) VALUES ('WAR AND PEACE',
             (SELECT g.GENRE_ID FROM GENRE g WHERE g.NAME = 'NOVEL'),
             (SELECT a.AUTHOR_ID FROM AUTHOR a WHERE a.FIRSTNAME = 'LEV' AND a.PATRONYMIC = 'NIKOLAEVICH' AND a.LASTNAME = 'TOLSTOY'));
INSERT INTO BOOK(NAME, GENRE_ID, AUTHOR_ID) VALUES ('ANNA KARENINA',
             (SELECT g.GENRE_ID FROM GENRE g WHERE g.NAME = 'NOVEL'),
             (SELECT a.AUTHOR_ID FROM AUTHOR a WHERE a.FIRSTNAME = 'LEV' AND a.PATRONYMIC = 'NIKOLAEVICH' AND a.LASTNAME = 'TOLSTOY'));