DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR (
    ID          BIGINT AUTO_INCREMENT,
    FIRSTNAME   VARCHAR2(255),
    PATRONYMIC  VARCHAR2(255),
    LASTNAME    VARCHAR2(255),
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE (
    ID          BIGINT AUTO_INCREMENT,
    NAME        VARCHAR2(255),
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK (
    ID          BIGINT AUTO_INCREMENT,
    NAME        VARCHAR2(255),
    GENRE       BIGINT NOT NULL,
    AUTHOR      BIGINT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (GENRE) REFERENCES GENRE(ID),
    FOREIGN KEY (AUTHOR) REFERENCES AUTHOR(ID)
);